name: phpunit-tests
run-name: Running PHPUnit tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: xdebug

      - name: Install composer dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --coverage-text
